// Copyright Oleg Maximenko 2014.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// See http://github.com/svgpp/svgpp for library home page.

SVGPP_ON(onfocusin)
SVGPP_ON(onfocusout)
SVGPP_ON(onactivate)
SVGPP_ON(onclick)
SVGPP_ON(onmousedown)
SVGPP_ON(onmouseup)
SVGPP_ON(onmouseover)
SVGPP_ON(onmousemove)
SVGPP_ON(onmouseout)
SVGPP_ON(onload)