// Copyright Oleg Maximenko 2014.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// See http://github.com/svgpp/svgpp for library home page.

SVGPP_ON(begin)
SVGPP_ON(dur)
SVGPP_ON(end)
SVGPP_ON(min)
SVGPP_ON(max)
SVGPP_ON(restart)
SVGPP_ON(repeatCount)
SVGPP_ON(repeatDur)
//SVGPP_ON(fill) // 'fill' conflicts with presentation attributes, so it is inserted manually on elements 
                 // without presentation attributes
