// Copyright Oleg Maximenko 2014.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// See http://github.com/svgpp/svgpp for library home page.

SVGPP_ON_NS(xlink, href)
SVGPP_ON_NS(xlink, show)
SVGPP_ON_NS(xlink, actuate)
SVGPP_ON_NS(xlink, type)
SVGPP_ON_NS(xlink, role)
SVGPP_ON_NS(xlink, arcrole)
SVGPP_ON_NS(xlink, title)
