// Copyright Oleg Maximenko 2014.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at
// http://www.boost.org/LICENSE_1_0.txt)
//
// See http://github.com/svgpp/svgpp for library home page.

SVGPP_ON(feBlend)
SVGPP_ON(feColorMatrix)
SVGPP_ON(feComponentTransfer)
SVGPP_ON(feComposite)
SVGPP_ON(feConvolveMatrix)
SVGPP_ON(feDiffuseLighting)
SVGPP_ON(feDisplacementMap)
SVGPP_ON(feFlood)
SVGPP_ON(feGaussianBlur)
SVGPP_ON(feImage)
SVGPP_ON(feMerge)
SVGPP_ON(feMorphology)
SVGPP_ON(feOffset)
SVGPP_ON(feSpecularLighting)
SVGPP_ON(feTile)
SVGPP_ON(feTurbulence)